### ISSUE TITLE
The ability to select another/disable the background

### ISSUE THREAD

**Issue by deevroman** [amandasaurus/osm-river-basins#2]
Have you tried using other backgrounds? (black and white or no backing at all) 

Now it is very inconvenient to look at green rivers, because they are poorly visible against the background of forests and fields (for example, the Volga river basin)

Thank you for this global map!

**Comment by amandasaurus** [comment]
On Sat, 15 Apr 2023 19:31 +02:00, Roman Deev ***@***.***> wrote:
> Have you tried using other backgrounds? (black and white or no backing at all)
>
> Now it is very inconvenient to look at green rivers, because they are 
> poorly visible against the background of forests and fields (for 
> example, the Volga river basin)

Yes I know! As a quick, simple fix, I've removed that shade of green. Is that good enough?

-- 
Amanda

**Comment by deevroman** [comment]
Yes, it's gotten better. Thanks!

**Comment by amandasaurus** [comment]
Do you have any suggested tile urls which I could add for the backgrounds? Then I can add them

**Comment by deevroman** [comment]
Perhaps you can embed terrain tiles that uses a similar site https://frexosm.ru/basin

But, the original reason for being able to change the substrate is that osmcarto introduces too much noise. Even no background layer might be better (look at the site above)
