### ISSUE TITLE
River shown as interrupted even if is not

### ISSUE THREAD

**Issue by ivanbranco** [amandasaurus/osm-river-basins#4]
For example here: https://amandasaurus.github.io/osm-river-basins/#map=16.65/45.631171/8.504851

![image](https://github.com/amandasaurus/osm-river-basins/assets/94002623/a863e814-a0ac-453c-b0bd-9f2222009733)

The river seems interrupted at the bridge. But in reality both the culvert at the bridge and the following part are correctly tagged as waterway=river

![image](https://github.com/amandasaurus/osm-river-basins/assets/94002623/da586f6f-9d1e-4142-b3aa-cd6b3dd59e69)

**Comment by amandasaurus** [comment]
That area appears to be fixed now. I have done some data updates since then.
There is a limitation in how we create vector tiles which can cause gaps. I don't think that's relevant here, but could be,
