### ISSUE TITLE
Creek omitted

### ISSUE THREAD

**Issue by clarisma** [amandasaurus/osm-river-basins#8]
Nice work!

Any idea why [this creek](https://www.openstreetmap.org/way/133068945) would be omitted? Its tributaries are showing up, but as unconnected ways:
![streams](https://github.com/amandasaurus/osm-river-basins/assets/56932851/643b2e76-897b-4be1-82c7-3f1861f8adb3)

It looks like the tributaries are noded properly in OSM.

Maybe the generalization you're applying to the linestrings is causing the vertexes to shift, so they're no longer coincident with the neighboring ways?

**Comment by clarisma** [comment]
It looks like your goal is to omit unnamed streams, but your filter is reversed: streams without names are showing up, named streams are excluded.

**Comment by amandasaurus** [comment]
I've done some data updates, and fixes, and that stream is now showing up. (The locations is [here](https://amandasaurus.github.io/osm-river-basins/#map=13.24/43.80727/7.66637&tiles=planet-waterway-all)).

![image](https://github.com/amandasaurus/osm-river-basins/assets/1547/5e9b440b-b3e1-4522-8f3b-531df35fdd3c)

Sometimes parts of river networks get dropped, but that's gotten better
